import { test, expect } from '@playwright/test'
import { writeFileSync, readFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { launch, shot } from './helpers'

test.describe('accounts', () => {
  test('switch, rotate and the command palette change the active account through the CLI', async () => {
    const { app, page, state } = await launch()
    await expect(page.getByTestId('account-row-1')).toHaveAttribute('data-active', 'true')

    await page.getByTestId('switch-2').click()
    await expect(page.getByRole('status')).toContainText('Switched to Account-2')
    await expect(page.getByTestId('account-row-2')).toHaveAttribute('data-active', 'true')
    await expect(page.getByTestId('active-pill')).toContainText('work@company.com')
    expect(state().activeAccountNumber).toBe(2)
    expect(state().log).toContainEqual(['switch', '2', '--json'])

    await page.getByTestId('rotate-menu').click()
    await page.getByRole('menuitem', { name: /Best/ }).click()
    // slot 3 has the most headroom but is disabled, so `best` lands on slot 1
    await expect(page.getByTestId('account-row-1')).toHaveAttribute('data-active', 'true')
    expect(state().log).toContainEqual(['switch', '--json', '--strategy', 'best'])

    await page.keyboard.press('Control+k')
    await expect(page.getByTestId('palette-input')).toBeFocused()
    await shot(page, 'palette')
    await page.getByTestId('palette-input').fill('company')
    await page.keyboard.press('Enter')
    await expect(page.getByTestId('account-row-2')).toHaveAttribute('data-active', 'true')
    expect(state().activeAccountNumber).toBe(2)
    await app.close()
  })

  test('alias, disable/enable and move go through the row menu', async () => {
    const { app, page, state } = await launch()
    await page.getByTestId('row-menu-2').click()
    await page.getByRole('menuitem', { name: /Set alias/ }).click()
    await page.getByTestId('alias-input').fill('work')
    await shot(page, 'dialog-alias')
    await page.getByTestId('alias-submit').click()
    // "work" alone would match the email — wait for the alias element itself
    await expect(page.getByTestId('alias-2')).toHaveText('work')
    expect(state().accounts['2'].alias).toBe('work')

    await page.getByTestId('row-menu-2').click()
    await page.getByRole('menuitem', { name: /Disable/ }).click()
    await expect(page.getByTestId('account-row-2')).toContainText('disabled')
    expect(state().accounts['2'].disabled).toBe(true)
    await page.getByTestId('row-menu-2').click()
    await page.getByRole('menuitem', { name: /Enable/ }).click()
    await expect(page.getByTestId('account-row-2')).not.toContainText('disabled')

    await page.getByTestId('row-menu-4').click()
    await page.getByRole('menuitem', { name: /Move to slot/ }).click()
    await page.getByTestId('move-input').fill('7')
    await page.getByTestId('move-submit').click()
    await expect(page.getByTestId('account-row-7')).toBeVisible()
    expect(state().accounts['7'].email).toBe('api-key-4@token.local')
    expect(state().log).toContainEqual(['move', '4', '7'])
    await app.close()
  })

  test('add from token hands the secret over stdin and the row appears', async () => {
    const { app, page, state } = await launch()
    await page.getByTestId('add-menu').click()
    await page.getByRole('menuitem', { name: /setup-token or API key/ }).click()
    await page.getByTestId('token-input').fill('sk-ant-oat01-VERY-SECRET-TOKEN')
    await page.getByPlaceholder('setup-token-N@token.local').fill('token@corp.com')
    await shot(page, 'dialog-token')
    await page.getByTestId('token-submit').click()
    await expect(page.getByTestId('account-row-5')).toContainText('token@corp.com')
    const s = state()
    expect(s.accounts['5'].email).toBe('token@corp.com')
    expect(JSON.stringify(s.log)).not.toContain('VERY-SECRET')
    expect(s.log).toContainEqual(['add-token', '-', '--email', 'token@corp.com'])
    await app.close()
  })

  test('add from the current login refreshes the list', async () => {
    const { app, page, state } = await launch()
    await page.getByTestId('add-menu').click()
    await page.getByRole('menuitem', { name: /current Claude login/ }).click()
    await page.getByTestId('add-alias').fill('fresh')
    await shot(page, 'dialog-add')
    await page.getByTestId('add-submit').click()
    await expect(page.getByRole('status')).toContainText('Added Account')
    expect(state().log).toContainEqual(['add', '--alias', 'fresh'])
    await app.close()
  })

  test('remove needs the slot or email typed, then confirms on stdin', async () => {
    const { app, page, state } = await launch()
    await page.getByTestId('row-menu-3').click()
    await page.getByRole('menuitem', { name: /Remove account/ }).click()
    await expect(page.getByTestId('remove-submit')).toBeDisabled()
    await page.getByTestId('remove-confirm').fill('nope')
    await expect(page.getByTestId('remove-submit')).toBeDisabled()
    await page.getByTestId('remove-confirm').fill('spare@example.com')
    await shot(page, 'dialog-remove')
    await page.getByTestId('remove-submit').click()
    await expect(page.getByTestId('account-row-3')).toHaveCount(0)
    expect(state().accounts['3']).toBeUndefined()
    expect(state().log).toContainEqual(['remove', '3'])
    await app.close()
  })

  test('a CLI failure shows the error and leaves the row untouched', async () => {
    const { app, page, state } = await launch({ env: { FAKE_CSWAP_FAIL: 'switch' } })
    await page.getByTestId('switch-2').click()
    await expect(page.getByRole('status')).toContainText('forced failure')
    await expect(page.getByTestId('account-row-1')).toHaveAttribute('data-active', 'true')
    expect(state().activeAccountNumber).toBe(1)
    await shot(page, 'toast-error')
    await app.close()
  })

  test('export and import use the file dialogs (stubbed) and run the CLI', async () => {
    const { app, state, statePath } = await launch()
    const dir = dirname(statePath)
    const file = join(dir, 'export.cswap')
    const stub = join(dir, 'dialogs.json')
    writeFileSync(stub, JSON.stringify({ saveFile: file, openFile: file }))
    // the env var must exist at launch, so relaunch on the same fake state
    await app.close()
    const l2 = await launch({ env: { CSWAP_DESKTOP_TEST_DIALOGS: stub, FAKE_CSWAP_STATE: statePath } })
    await l2.page.getByTestId('more-menu').click()
    await l2.page.getByRole('menuitem', { name: /Export all/ }).click()
    await shot(l2.page, 'dialog-export')
    await l2.page.getByTestId('export-submit').click()
    await expect(l2.page.getByRole('status')).toContainText('Exported')
    expect(existsSync(file)).toBe(true)
    expect(JSON.parse(readFileSync(file, 'utf8')).accounts).toHaveLength(4)

    await l2.page.getByTestId('more-menu').click()
    await l2.page.getByRole('menuitem', { name: /Import/ }).click()
    await l2.page.getByRole('switch', { name: 'Overwrite existing' }).click()
    await l2.page.getByTestId('import-submit').click()
    await expect(l2.page.getByRole('status').first()).toContainText('Import finished')
    expect(state().log).toContainEqual(['import', file, '--force'])
    await l2.app.close()
  })
})

test.describe('extras', () => {
  test('token diagnostics dialog shows --token-status output; Check now runs auto --once', async () => {
    const { app, page, state } = await launch()
    await page.getByTestId('more-menu').click()
    await page.getByRole('menuitem', { name: /Token diagnostics/ }).click()
    await expect(page.getByTestId('diag-output')).toContainText('Account-1: you@example.com')
    expect(state().log).toContainEqual(['list', '--token-status'])
    await shot(page, 'dialog-diag')
    await page.keyboard.press('Escape')
    await page.getByTestId('nav-auto').click()
    await page.getByTestId('auto-once').click()
    await expect(page.getByRole('status')).toContainText('Nothing to do')
    await expect(page.getByTestId('auto-feed')).toContainText('below-threshold')
    expect(state().log).toContainEqual(['auto', '--once', '--json'])
    await app.close()
  })
})

test.describe('other pages', () => {
  test('auto-switch starts the child, streams events, saves config, stops', async () => {
    const { app, page, state } = await launch({ env: { FAKE_CSWAP_AUTO_INTERVAL: '0.3' } })
    await page.getByTestId('nav-auto').click()
    await page.getByTestId('auto-toggle').click()
    await expect(page.getByTestId('auto-toggle')).toContainText('Stop')
    await page.getByRole('button', { name: 'All' }).click()
    await expect(page.getByTestId('auto-feed')).toContainText('poll')
    await expect(page.getByTestId('auto-feed')).toContainText('sleep')
    await shot(page, 'auto-running')
    // config write goes through `cswap config set`
    const thr = page.getByTestId('cfg-autoswitch.threshold').getByRole('spinbutton')
    await thr.fill('80')
    await thr.press('Enter')
    await expect(page.getByRole('status').first()).toContainText('autoswitch.threshold = 80')
    expect(state().settings['autoswitch.threshold']).toBe(80)
    await page.getByTestId('auto-toggle').click()
    await expect(page.getByTestId('auto-toggle')).toContainText('Start')
    await expect(page.getByText(/Stopped|Exited/)).toBeVisible()
    await app.close()
  })

  test('mappings: add via the directory picker stub and unmap', async () => {
    const { app, state, statePath } = await launch()
    const stub = join(dirname(statePath), 'dialogs.json')
    writeFileSync(stub, JSON.stringify({ directory: '/tmp/picked-project' }))
    await app.close()
    const l2 = await launch({ env: { CSWAP_DESKTOP_TEST_DIALOGS: stub, FAKE_CSWAP_STATE: statePath } })
    await l2.page.getByTestId('nav-mappings').click()
    await expect(l2.page.getByTestId('mapping-row')).toHaveCount(1)
    await l2.page.getByTestId('map-add').click()
    await l2.page.getByRole('button', { name: 'Browse' }).click()
    await expect(l2.page.getByTestId('map-path')).toHaveValue('/tmp/picked-project')
    await l2.page.getByTestId('map-account').selectOption('2')
    await shot(l2.page, 'dialog-map')
    await l2.page.getByTestId('map-submit').click()
    await expect(l2.page.getByTestId('mapping-row')).toHaveCount(2)
    expect(state().mappings['/tmp/picked-project']).toMatchObject({ email: 'work@company.com' })
    await l2.page.getByTestId('unmap').first().click()
    await expect(l2.page.getByTestId('mapping-row')).toHaveCount(1)
    await l2.app.close()
  })

  test('settings persist across restarts (theme + refresh interval) and the log page lists calls', async () => {
    const { app, page, userData } = await launch()
    await page.getByTestId('nav-settings').click()
    await page.getByRole('radio', { name: 'Dark' }).click()
    await page.getByRole('combobox', { name: 'Refresh interval' }).selectOption('300')
    await expect(page.locator('html')).toHaveClass(/dark/)
    await app.close()
    const saved = JSON.parse(readFileSync(join(userData, 'settings.json'), 'utf8'))
    expect(saved).toMatchObject({ theme: 'dark', refreshSeconds: 300 })
    const l2 = await launch({ settings: saved })
    await expect(l2.page.locator('html')).toHaveClass(/dark/)
    await l2.page.getByTestId('nav-log').click()
    await expect(l2.page.getByTestId('log-row').first()).toContainText('cswap')
    await l2.page.getByTestId('log-row').first().click()
    await shot(l2.page, 'log-dark-expanded')
    await l2.app.close()
  })

  test('without cswap the onboarding screen shows and a custom path recovers', async () => {
    const { app, page } = await launch({ bin: '/definitely/not/here/cswap' })
    await expect(page.getByTestId('onboarding')).toBeVisible()
    await expect(page.getByTestId('sidebar-status')).toContainText('not found')
    await shot(page, 'onboarding')
    await page.getByTestId('nav-settings').click()
    await page.getByTestId('cswap-path').fill(process.platform === 'win32' ? join(process.cwd(), 'test', 'fake-cswap', 'fake-cswap.cmd') : join(process.cwd(), 'test', 'fake-cswap', 'fake-cswap.mjs'))
    await page.getByTestId('cswap-path-save').click()
    await expect(page.getByTestId('sidebar-status')).toContainText('cswap 0.25.0')
    await page.getByTestId('nav-accounts').click()
    await expect(page.getByTestId('accounts-table')).toBeVisible()
    await app.close()
  })
})
